### ISSUE TITLE
seems to confuse \r for letters

### ISSUE THREAD

**Issue by mmulder72** [Kirito139/wordLadderSolver#6]
I cloned and ran word_ladder_solver.py and got this result:
```
$python word_ladder_solver.py 
['core', 'cor\r', 'coe\r', 'cee\r', 'see\r', 'seed']
['core', 'cor\r', 'coe\r', 'soe\r', 'see\r', 'seed']
```

**Comment by mmulder72** [comment]
It depends on the python version. If I use python3 I get \n instead of \r:
```
$python3 word_ladder_solver.py
['core', 'cor\n', 'coe\n', 'cee\n', 'see\n', 'seed']
['core', 'cor\n', 'coe\n', 'soe\n', 'see\n', 'seed']
```

**Comment by Kirito139** [comment]
neither of those happen with me. check that you're on the latest version of python.

**Comment by mmulder72** [comment]
I upgraded from Python 3.7 to 3.9 and had to remove `fourLetterWords.txt`. It works now.
